version: '3.8'

services:
  tareas-app:
    build: .
    container_name: tareas-app
    ports:
      - "8080:8080"
    depends_on:
      - tareas-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://tareas-db:5432/tareasdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - tareas-net

  tareas-db:
    image: postgres:15
    container_name: tareas-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tareasdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tareas-net

volumes:
  pgdata:

networks:
  tareas-net:
    driver: bridge
