version: "3.8"
services:

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
    networks:
      - mentia-net

  backend:
    build: ./backend-mentia
    container_name: mentia-backend
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - keycloak
    networks:
      - mentia-net

networks:
  mentia-net:
    driver: bridge
