name: Codecov Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Generate Coverage Report
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v3

    - name: ☕ Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: 🛠 Build with Maven
      run: mvn clean verify --no-transfer-progress

    - name: 📤 Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # solo si es repositorio privado
        files: ./target/site/jacoco/jacoco.xml
        flags: unittests
        name: codecov-coverage
